spring:
  profiles:
    active: dev
my:
  #作者
  author: johnDeng
  #生成文件的包总路径
  packgePath: com.design.framework
  #模板的总路径
  templateBasePath: classpath:template/
  #生成文件的总路径
  writeFileBasePath: G:\eclispe\spring-boot-code-generator\src\main\resources\write\
  #数据库表前缀
  tablePrefix: t_
  #继承类路径
  extendsBasePath: com.design.framework.base