spring:
  profiles:
    active: dev
my:
  #作者
  author: johnDeng
  #生成文件的包总路径
  packgePath: com.design.framework
  #模板的总路径
  templateBasePath: classpath:template/
  #生成文件的总路径
  writeFileBasePath: E:\mayun\spring-boot-code-generator\src\main\resources\write\
  #数据库表前缀
  tablePrefix: t_
  #继承类路径
  extendsBasePath: com.design.framework.base
  #mysql url
  url: jdbc:mysql://47.106.195.105:3306/synthesis_portal_dev?useUnicode=true&characterEncoding=UTF-8&useSSL=false&autoReconnect=true&failOverReadOnly=false&serverTimezone=GMT%2b8
  #mysql 用户名
  username: ht
  #mysql 密码
  password: Bigdata_1
  
  