server:
  port: 10000
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${codegenerator.datasource.url}
    username: ${codegenerator.datasource.username}
    password: ${codegenerator.datasource.password}
    
codegenerator:
  #全局配置
  global:
    #作者
    author: johnDeng
    #生成文件的包总路径
    packge-path: org.john.codebuilder
    #模板的总路径
    template-base-path: classpath:template/
    #生成文件的总路径(绝对路径)
    write-file-base-path: E:\mayun\spring-boot-code-generator\src\main\resources\write\
    #数据库表前缀
    table-prefix: t_
    #mybatis mapper namespace 前缀 
    mapper-namespace:
    #是否需要模块名称
    need-model: true 
    #功能模块名称
    module-name: test
    #mybatis生成的路径
    mapper-path: F:\粤通卡项目\互联网综合管理系统\code-generator\src\main\resources\write\mapper
    
    
  #继承配置
  extends:
    #需要继承Entity父类
    extends-base-entity: true
    #继承Entity父类：包+名称，不用写文件后缀
    base-entity-path:  com.design.framework.base.controller.BaseEntity
    
    #需要继承DAO父类
    extends-base-dao: true
    #继承DAO父类：包+名称，不用写文件后缀
    base-dao-path: com.design.framework.base.dao.BaseDao
    
    #需要继承Service父类
    extends-base-service: true
    #继承Service父类：包+名称，不用写文件后缀
    base-service-path: com.design.framework.base.service.BaseService
    
    #需要继承ServiceImpl父类
    extends-base-service-impl: true
    #继承ServiceImpl父类：包+名称，不用写文件后缀
    extends-base-service-impl-path: com.design.framework.base.service.impl.BaseServiceImpl
     
    #需要继承Controller父类
    extends-base-controller: true
    #继承Controller父类：包+名称，不用写文件后缀
    extends-base-controller-path: com.design.framework.base.controller.BaseController
    
  #数据库配置
  datasource:  
    #mysql url
    url: jdbc:mysql://10.88.1.80:3306/unitoll_internet_cms?useUnicode=true&characterEncoding=UTF-8&useSSL=false&autoReconnect=true&failOverReadOnly=false&serverTimezone=GMT%2b8
    #mysql 用户名
    username: root
    #mysql 密码
    password: hgrica1@
  
  